export namespace JsSpace {
    export enum Location {
        ALIAS_PREFIX,
        ARROW_FUNCTION_PREFIX,
        ARROW_FUNCTION_ARROW,
        DEFAULT_TYPE_PREFIX,
        DEFAULT_TYPE_BEFORE_EQUALS,
        DELETE_PREFIX,
        EXPORT_PREFIX,
        EXPORT_FROM,
        FUNCTION_TYPE_PREFIX,
        FUNCTION_TYPE_ARROW,
        JS_IMPORT_PREFIX,
        JS_IMPORT_FROM,
        JS_BINARY_PREFIX,
        JS_OPERATOR_PREFIX,
        OBJECT_BINDING_DECLARATIONS_PREFIX,
        OBJECT_BINDING_DECLARATIONS_BINDING_PREFIX,
        OBJECT_BINDING_DECLARATIONS_BINDING_AFTER_VARARG,
        TEMPLATE_EXPRESSION_PREFIX,
        TEMPLATE_EXPRESSION_VALUE_PREFIX,
        TEMPLATE_EXPRESSION_VALUE_AFTER,
        TUPLE_PREFIX,
        TYPE_DECLARATION_PREFIX,
        TYPE_OPERATOR_PREFIX,
        UNARY_PREFIX,
        UNION_PREFIX,
    }
}
export namespace JsLeftPadded {
    export enum Location {
        EXPORT_INITIALIZER,
        JS_IMPORT_INITIALIZER,
        JS_BINARY_OPERATOR,
        JS_OPERATOR_OPERATOR,
        OBJECT_BINDING_DECLARATIONS_INITIALIZER,
        OBJECT_BINDING_DECLARATIONS_BINDING_DIMENSIONS_AFTER_NAME,
        OBJECT_BINDING_DECLARATIONS_BINDING_INITIALIZER,
        TYPE_DECLARATION_INITIALIZER,
        TYPE_OPERATOR_EXPRESSION,
        UNARY_OPERATOR,
    }
}
export namespace JsRightPadded {
    export enum Location {
        ALIAS_PROPERTY_NAME,
        JS_IMPORT_NAME,
        OBJECT_BINDING_DECLARATIONS_BINDING_PROPERTY_NAME,
        TEMPLATE_EXPRESSION_TAG,
        UNION_TYPES,
        COMPILATION_UNIT_STATEMENTS,
    }
}
export namespace JsContainer {
    export enum Location {
        EXPORT_EXPORTS,
        FUNCTION_TYPE_PARAMETERS,
        JS_IMPORT_IMPORTS,
        OBJECT_BINDING_DECLARATIONS_BINDINGS,
        TUPLE_ELEMENTS,
    }
}
