---
name: ci

on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: 0 18 * * *

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  GRADLE_SWITCHES: --console=plain --info --stacktrace --warning-mode=all --no-daemon
  RELEASE_BUILD: "true"

jobs:
  build:
    uses: openrewrite/gh-automation/.github/workflows/ci-gradle.yml@main
    secrets:
      gradle_enterprise_access_key: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      gradle_enterprise_cache_username: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
      gradle_enterprise_cache_password: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
      ossrh_username: ${{ secrets.OSSRH_USERNAME }}
      ossrh_token: ${{ secrets.OSSRH_TOKEN }}
      ossrh_signing_key: ${{ secrets.OSSRH_SIGNING_KEY }}
      ossrh_signing_password: ${{ secrets.OSSRH_SIGNING_PASSWORD }}

  node-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - uses: gradle/actions/setup-gradle@v4
        with:
          validate-wrappers: true

      - name: build
        run: (./gradlew ${{ env.GRADLE_SWITCHES }} build)

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: openrewrite/package-lock.json
      - run: npm ci
        working-directory: openrewrite
      - run: npm run build
        working-directory: openrewrite
      - run: npm run test
        working-directory: openrewrite
